### ISSUE TITLE
parse_format_replacements_xml mishandles multi-line replacements

### ISSUE THREAD

**Issue by nclark-nasuni** [cpp-linter/cpp-linter#168]
`parse_format_replacements_xml` uses `get_line_cnt_from_cols` to determine which line is being updated, which indicates on which line the replacement starts but the replacement can span multiple lines into the lines which changed when `lines_changed_only` is set.

Example code
```
#include <string>

class Test {
public:
    const std::string getString() const { return str_member_; }

    std::string toString() const {
            return std::string("Test[string:") + str_member_ + ", int: " + int_member + "]";
    }

private:
    std::string str_member_{};
    int         int_member_{};
}
```

If formatter is run only on lines 8:9
```
$ /usr/bin/clang-format -style=file --output-replacements-xml --lines=8:9 test.cpp 
<?xml version='1.0'?>
<replacements xml:space='preserve' incomplete_format='false'>
<replacement offset='139' length='13'>&#10;        </replacement>
</replacements>
```
The offset is 139 which when run through `get_line_cnt_from_cols` returns line 7 which is not in the range 8:9 so the replacement will be ignored. The `parse_format_replacements_xml` needs to take into consideration the entire range of the replacement to see if it ends in the line range or trust that clang will only format the specified lines so that all replacements pertain to the lines specified and the line check can be removed.

**Comment by 2bndy5** [comment]
First, thank you for raising the issue. 

Secondly, I have to ask you to _stop_ using run-on sentences. Even for people that speak English natively, your writing style is very difficult to understand. FYI, not everyone on the cpp-linter dev team speaks English natively. 

Finally, I think your concern here is a matter of interpretation.

1. It sounds like you expect `get_line_cnt_from_cols` to return a range of lines instead of the starting line. This seems reasonable.
2. I think you also expect the XML replacement to be included if the original line(s) is within the range of altered line(s). This is where I have to disagree.

   We've had some issues in the past where unexpected/undesired replacements were reported. The reported replacements were unexpected/undesired because they altered lines that were not part of the lines changed in the git diff.

I need some time to think about what you're talking about because it is rather confusingly started. It seems like there is actually 2 separate issues involved.

**Comment by 2bndy5** [comment]
What you're requesting is not a simple solution. We would need to
1. Compare the difference between original text and replacement text to get the actual alterations. Possibly use [`difflib.SequenceMatcher`](https://docs.python.org/3/library/difflib.html#sequencematcher-objects).
2. Calculate the line number(s) from the actual alterations' removed text (not including line numbers of any added lines). Preferably, this would be a continuous range of line numbers, but it could also be non-continuous range of line numbers (depending on the changes being applied).

Are you willing to submit a PR for this? If not, I doubt that this kind of complexity would be added any time soon. I still think this is an issue that is better resolved at the clang-format level.

PS - I think that clang-format backtracks to the first non-whitespace character to enforce the appropriate line endings (`\n` vs `\r\n`) and indentation characters (`\t` vs `\s`) in the replacement text. LLVM tooling has a long history of being a lot stricter than new-commers might expect.

**Comment by nclark-nasuni** [comment]
Yes, using `diff` instead of `true` might work for my scenario, but I think there is still an issue. I believe it comes down to the definition of when a line starts.
* Clangs tooling counts the `\n` as the first character in the next line
* `parse_format_replacements_xml` and `get_line_cnt_from_cols` count the `\n` as the last character in the previous line
ie
This is how clang interprets line numbers
```
This is line 1
\nThis is line 2 
\nThis is line 3
```
but this tool interprets it as
```
This is line 1\n
This is line 2\n
This is line 3
```
I think this could be detected trivially by testing if the first characters starting at the offset are either `\n` or `\r\n` and incrementing the starting line number by 1. If this seems like a reasonable solution to you I can submit a PR with this fix.

**Comment by 2bndy5** [comment]
Again, I'm not interested in a shortsighted one-liner that really only solves your particular example.

**Comment by 2bndy5** [comment]
I going with a comprehensive solution in rust (cpp-linter v2): Don't use XML output from clang-format. Instead, we'd just cache the changes from clang-format and use the diff between the changes and the original input. Then we can properly filter out any format changes that reach beyond the limits of the changed lines in the event's diff. See cpp-linter/cpp-linter-rs#347.

Also, moving away from clang-format's XML output means we can avoid bugs in clang-format's XML output; see cpp-linter/cpp-linter-action#250 for an edge-case example.
